theme: jekyll-theme-minimal
title: KETCube - The Prototyping and Educational IoT Platfor
description: KETCube project consists of several projects The current platform release is 0.1.1
logo: logo.png
logo_oshw: oshw-logo-200-px.png
show_downloads: true
github:
  maintainer: smartCampus ZČU
  maintainer_url: https://github.com/SmartCAMPUSZCU
  logo_mt: logo-sc.svg
  is_project_page: false
  fw_name: KETCube-fw
  fw_zip_url: https://github.com/SmartCAMPUSZCU/KETCube-fw/archive/v0.1.1.zip
  fw_tar_url: https://github.com/SmartCAMPUSZCU/KETCube-fw/archive/v0.1.1.tar.gz
  fw_repository_url: https://github.com/SmartCAMPUSZCU/KETCube-fw
  docs_name: KETCube-docs
  docs_zip_url: https://github.com/SmartCAMPUSZCU/KETCube-docs/archive/v0.1.1.zip
  docs_tar_url: https://github.com/SmartCAMPUSZCU/KETCube-docs/archive/v0.1.1.tar.gz
  docs_repository_url: https://github.com/SmartCAMPUSZCU/KETCube-docs
  mainBoard_name: KETCube-mainBoard
  mainBoard_zip_url: https://github.com/SmartCAMPUSZCU/KETCube-mainBoard/archive/v0.1.0.zip
  mainBoard_tar_url: https://github.com/SmartCAMPUSZCU/KETCube-mainBoard/archive/v0.1.0.tar.gz
  mainBoard_repository_url: https://github.com/SmartCAMPUSZCU/KETCube-mainBoard
  
